# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURAÇÕES DO HIBERNATE / JPA
# ===============================
# update: Cria ou atualiza as tabelas automaticamente com base nas Entidades Java. 
# (Em produção, o ideal é usar 'validate' e gerenciar com Flyway, mas 'update' é perfeito para o MVP)
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries no console para facilitar o debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# INTEGRAÇÕES EXTERNAS
# ===============================
mercadopago.api-url=https://api.mercadopago.com
mercadopago.access-token=${MERCADOPAGO_TOKEN}
mercadopago.webhook-url=https://annually-mounted-carol.ngrok-free.dev/api/webhooks/mercadopago

# ===============================
# CONFIGURAÇÕES DO SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURAÇÕES DE SEGURANÇA (JWT)
# ===============================
api.jwt.secret=SUA_CHAVE_SUPER_SECRETA_E_LONGA_PARA_O_AMBIENTE_DE_DESENVOLVIMENTO
